# Generated by Django 3.0 on 2020-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='bio',
            field=models.CharField(default='A newshub content creator', max_length=150),
        ),
    ]
