# Generated by Django 3.0 on 2020-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201001_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='acct_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='acct_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
