# Generated by Django 3.0 on 2020-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201203_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
