# Generated by Django 3.0 on 2020-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_creatorprofile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
