# Generated by Django 2.2.10 on 2021-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Moreme Hub', max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('tcc', 'To All Creators'), ('tam', 'To ALl Members')], default='tcc', max_length=10, null=True)),
                ('already_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
