# Generated by Django 2.2.10 on 2021-04-27 16:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210427_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmail',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkmail',
            name='type',
            field=models.CharField(blank=True, choices=[('tcc', 'To All Creators'), ('tam', 'To All Members')], default='tcc', max_length=10, null=True),
        ),
    ]
