# Generated by Django 3.1.4 on 2021-05-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210427_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmail',
            name='message',
            field=models.TextField(default='Moreme Hub'),
        ),
    ]
