# Generated by Django 3.0 on 2020-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, default='blue', max_length=250, null=True, verbose_name='Color Code'),
        ),
    ]
