# Generated by Django 3.0 on 2020-10-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20201008_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default='general', null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='Category'),
        ),
    ]
