# Generated by Django 3.0 on 2020-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='ip_address',
            field=models.TextField(default='()'),
        ),
    ]
