# Generated by Django 3.0 on 2020-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_view_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
