# Generated by Django 3.0 on 2020-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20201110_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip_address',
            field=models.TextField(default='[]'),
        ),
    ]
