# Generated by Django 3.0 on 2020-11-14 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0018_auto_20201110_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='articles_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, default='bg-primary', max_length=250, null=True, verbose_name='Color Code'),
        ),
    ]
