# Generated by Django 3.0 on 2020-11-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
