# Generated by Django 3.0 on 2020-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20201115_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='trend_for',
            field=models.CharField(choices=[('unlimited', 'unlimited'), ('6h', '6h'), ('12h', '12h'), ('1d', '1d'), ('2d', '2d'), ('no', 'No')], default='unlimited', max_length=10),
        ),
    ]
