# Generated by Django 3.0 on 2020-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_article_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reject_reason',
            field=models.CharField(default='Your article violates publishing guidlines', max_length=200),
        ),
    ]
