# Generated by Django 3.0 on 2020-11-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20201126_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reject_reason',
            field=models.CharField(blank=True, default='Your article violates publishing guidlines', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='trend_for',
            field=models.CharField(blank=True, choices=[('unlimited', 'unlimited'), ('6h', '6h'), ('12h', '12h'), ('1d', '1d'), ('2d', '2d'), ('no', 'No')], default='unlimited', max_length=10, null=True),
        ),
    ]
