# Generated by Django 3.0 on 2020-11-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20201128_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revise',
            field=models.BooleanField(default=False),
        ),
    ]
