# Generated by Django 2.2.10 on 2021-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_article_revise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, default='ANON', max_length=250, null=True),
        ),
    ]
