# Generated by Django 2.2.10 on 2021-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20210202_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='ads')),
                ('link', models.URLField()),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
    ]
