# Generated by Django 2.2.10 on 2021-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
