# Generated by Django 2.2.10 on 2021-04-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_advertise_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='articles.Category'),
        ),
    ]
