# Generated by Django 2.2.10 on 2021-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_advertise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='ppa', max_length=10, null=True),
        ),
    ]
