<<<<<<< HEAD
# Generated by Django 2.2.10 on 2021-04-26 20:27
=======
# Generated by Django 3.1.4 on 2021-04-27 08:00
>>>>>>> 495db788d289fdede0b16c52d87caa111a101f68

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_advertise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='ppa', max_length=10, null=True),
=======
            field=models.CharField(blank=True, choices=[('ppa', 'PPA'), ('ppc', 'PPC')], default='ppa', max_length=10, null=True),
>>>>>>> 495db788d289fdede0b16c52d87caa111a101f68
        ),
    ]
