# Generated by Django 2.2.10 on 2021-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, choices=[('ppa', 'PPA'), ('ppc', 'PPC')], default='ppa', max_length=10, null=True),
        ),
    ]
