# Generated by Django 3.1.4 on 2021-05-15 11:35

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20210515_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
