# Generated by Django 3.1.4 on 2021-05-15 12:01

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20210515_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
