# Generated by Django 3.0 on 2020-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
